### ISSUE TITLE
Template is missing in ruby 2.0

### ISSUE THREAD

**Issue by anoam** [activescaffold/active_scaffold#250]
Hi!

I have active scaffold controller:

class StatusesController < ApplicationController
  active_scaffold :status
end

When I try to run it on test server with WEBrick or unicorn, it returns:

Template is missing

Missing template statuses/index, application/index, active_scaffold_overrides/index with {:locale=>[:ru], :formats=>[:html], :handlers=>[:erb, :builder, :coffee]}. Searched in: \* "/home/webtest/project/app/views" \* "/home/webtest/.rvm/gems/ruby-2.0.0-p0@project/gems/active_scaffold-3.3.0.rc2/app/views" \* "/home/webtest/.rvm/gems/ruby-2.0.0-p0@project/gems/devise-2.2.3/app/views"

Prompt please what is wrong?

**Comment by FelixFortis** [comment]
For what it's worth, I had this issue locally, and it turned out that I had a capital letter in one of my directory names.
OSX Yosemite 10.10.5 moving from Ruby 1.9.3 to 2.3.1

Typing the following into my console revealed the app was looking for that directory, but all lowercase.
{{[1] pry(main)> puts LoginController.view_paths.map(&:to_s)}}
