### ISSUE TITLE
Namespaced model names cannot be rendered as subviews

### ISSUE THREAD

**Issue by jasonfb** [activescaffold/active_scaffold#481]
see https://groups.google.com/forum/#!topic/activescaffold/7mVoW8lYYuY for backgorund

I am examining the code inside of action_view_rendering.rb and working on a patch to fix this problem. I believe I can do this full backwards-compatible, so that existing scaffolds built will fallback on the current behavior but that there will be a way to specify that a model name cannot be inferred from the controller name. 

Since it is entirely likely for a large app to namespace controllers but not necessarily namespace models *in the same exact way* (for example, my controller is Admin::Scaffold::PagesController but my object is Platform::Page), I believe this dependency on having single-level models only and inferring models based on these controller path actually creates a tightly-coupled dependency that should be fixed.

**Comment by courtland** [comment]
First off, it would be helpful to post the entire backtrace of the exception. I'm basing this off the fact that you claimed the problematic line is https://github.com/activescaffold/active_scaffold/blob/master/lib/active_scaffold/extensions/action_view_rendering.rb#L76

But I think i've run into this problem as well. It happens when the render_with_active_scaffold method successfully infers the path/namespace to your Controller, but is not able to infer the Model's class from the path to the controller (the :active_scaffold parameter supplied to the method).

This line here:
```ruby
model = remote_controller.to_s.sub(/.*\//, '').singularize
```
is simply trying to figure out the name of the Model in order to supply a label for the h2 element via:
```ruby
active_scaffold_config_for(model).list.label
```
At this point it has not actually executed any of the scaffold controller's code but is merely supplying a div for it to be rendered into via AJAX.

I've worked around this by suppling a :label argument to the render scaffold call. e.g.,
```ruby
render active_scaffold: 'foos/bars', label: 'Bar'
```

This essentially skips the call to active_scaffold_config_for() that is causing the exception:
```ruby
link_to(args.first[:label] || active_scaffold_config_for(model).list.label
```

Sergio may have a better way to fix this if there is a way to infer your Model name from the Controller path and that is simply not being figured out correctly, but I definitely have some controllers where this is not possible for various reasons (i.e., the controller name doesn't contain the model name in any way).

If you are able to load the scaffold's controller directly but not render it inline then that is likely your problem.

**Comment by jasonfb** [comment]
Yes thanks, adding the label to the params indeed solves the issue!
