### ISSUE TITLE
Force to rebuild a column options after an action.

### ISSUE THREAD

**Issue by AlexandruCD** [activescaffold/active_scaffold#523]
I have column defined in the config block, that it's not virtual, but the options used in the select tag for it are pulled via a function that returns an array of arrays, based on some database data. Now the problem is, after i create a record of one type, i need the options to be calculated again(they are cached i guess), and that select option that i used at the last create to be excluded next time i hit Create and the subform for create renders.
Is that somehow achievable?

**Comment by scambra** [comment]
If column is an association they are calculated in each request from database, they only are cached for same request, so if you edit a record with many records in subform we query db only for first record in subform.

If column is not association, options came from config.columns[:column_name].options[:options], you set them in config block, which is only evaluated at app start. To calculate on each request, define active_scaffold_enum_options instead of setting options[:options]

```ruby
def active_scaffold_enum_options(column, record)
  if column == :column_name
    # return calculated options
  else
    super
  end
end

**Comment by AlexandruCD** [comment]
Oh, well, after checking the source code, seem that you suggest me to fork the repo and use my own version of active_scaffold_enum_options? Defining it in my controller won't override the original definition from form_column_helpers.rb Not even defining it into my own module mix(ActiveScaffold->Helpers->FormColumnHelpers). I am missing something?

**Comment by scambra** [comment]
No, you don't need to fork. active_scaffold_enum_options is a helper method, to use in views, you may define it in your helper file to override result for some column and use super to keep usual behavior for other columns.

**Comment by AlexandruCD** [comment]
Ok, thank you for you quick replies and for your time. Cheers.

**Comment by scambra** [comment]
It's similar to other helper overrides, such as options_for_association_conditions helper used for association options: https://github.com/activescaffold/active_scaffold/wiki/Custom-Association-Options

I have added some info on this to https://github.com/activescaffold/active_scaffold/wiki/Enum-Columns
