### ISSUE TITLE
Not unique table/alias when using search.columns and includes with the same table

### ISSUE THREAD

**Issue by rovalcor** [activescaffold/active_scaffold#531]
I want to search a related table and then another table via a through relationship. For example I have the following code

```
config.search.columns = [:organization, :account_owner]
config.columns << :account_owner
config.columns[:account_owner].search_sql = "users.email"
config.columns[:account_owner].includes = {organization: :account_owner}
```

`:account_owner` is a User with a a belongs_to relationship in `:organization` and I want to search related users by their email address however I get the following error:

```
ActiveRecord::StatementInvalid (Mysql2::Error: Not unique table/alias: 'organizations': SELECT DISTINCT COUNT(DISTINCT `source_table`.`id`) FROM `source_table` LEFT OUTER JOIN `organizations` ON `organizations`.`id` = `source_table`.`organization_id` LEFT OUTER JOIN `organizations` ON `organizations`.`id` = `source_table`.`organization_id` LEFT OUTER JOIN `users` ON `users`.`id` = `organizations`.`account_owner_id` WHERE (organizations.name LIKE '%test%' OR `source_table`.`id` = 0 OR users.email LIKE '%test%')):
```

This is happening because its generating two left outer joins using `organizations` without using aliases. This used to work in Rails 4.2.6, but not since I upgraded to Rails 5.0.0.1.  Is this a bug or should I change the config?

**Comment by scambra** [comment]
Rails 4.2 doesn't have left_joins, and ActiveScaffold is using own implementation for it. Rails 5 added left_joins, so ActiveScaffold don't use own implementation and uses rails 5 one. That's may be reason to get different query in those versions.

However, if model has account_owner as through association, you don't need to add organization to includes. Try removing includes line, so organizations is not included twice (only would be included by left_joins(:account_owner) because is has_one through association)
