### ISSUE TITLE
Chosen: removing "- select -" option

### ISSUE THREAD

**Issue by spatarel** [activescaffold/active_scaffold#541]
I'm using chosen for 1:M and M:M relations. I was trying to get rid of the "- select -" option on top of the list and found two solutions:
(1) The one that I think should work but doesn't:
```
config.columns[:column_name].form_ui = :chosen
config.columns[:column_name].show_blank_record = false
```

(2) The one that works but it looks like a workaround to me:
```
config.columns[:column_name].form_ui = :chosen
config.columns[:column_name].options = {:include_blank => nil}
```

Note: I'm using active_scaffold (3.4.41.1).

I'm new to activescaffold and was wondering if this is an issue or not. Thank you!

**Comment by scambra** [comment]
One doesn't work because show_blank_record is related to subforms, when displaying subform ActiveScaffold by default whould display a blank record.

Right way is using include_blank, the same way to remove - select - option for select fields. Chosen is using select method in rails to render a select tag and convert it to chosen with JS
