### ISSUE TITLE
"Create New" available even when using Devise and not logged in

### ISSUE THREAD

**Issue by tripodrob** [activescaffold/active_scaffold#555]
I'm using Devise and have added the security methods in my models, but the "Create New" actions are still visible when not logged in.  The "Edit" and "Delete" actions are greyed out, but not the new option.

In models:
  def authorized_for_update?
    current_user != nil ? true : false
  end
  def authorized_for_delete?
    current_user != nil ? true : false
  end
  def authorized_for_create?
    current_user != nil ? true : false
  end

In order the stop the new action I had to add the security method to the controllers:
  def create_authorized?
    current_user != nil ? true : false
  end

**Comment by scambra** [comment]
El viernes, 26 de mayo de 2017 15:41:27 (CEST) Robbie Bingler escribió:
> I'm using Devise and have added the security methods in my models, but the
> "Create New" actions are still visible when not logged in.  The "Edit" and
> "Delete" actions are greyed out, but not the new option.
> 
> In models:
>   def authorized_for_update?
>     current_user != nil ? true : false
>   end
>   def authorized_for_delete?
>     current_user != nil ? true : false
>   end
>   def authorized_for_create?
>     current_user != nil ? true : false
>   end
> 
You should use class method (def self.authorized_for_create?). Instance method 
is never used for create, because it's checked before record exists. To sum 
up, collection links only check class method, record links check class method 
(if forbidden no link is displayed), then instance method (if forbidden link 
is disabled).

> In order the stop the new action I had to add the security method to the
> controllers: def create_authorized?
>     current_user != nil ? true : false
>   end

**Comment by tripodrob** [comment]
Ok, great.
Thanks
