### ISSUE TITLE
The row wasn't updated after the message was closed

### ISSUE THREAD

**Issue by AlexGHub13** [activescaffold/active_scaffold#578]
Hello, I have the problem with update row after message was closed.
I use the gem 'active_scaffold' v.3.4.43 and Ruby on Rails v 4.2.10 
I use two links (: type => member). I also use #action_name} _autohorized? methods for this links. Old version active_scaffold refreshes row and other link became active('startup' or 'shutdown'). In new version I must update the page, after pressed link. Maybe I'm using this tool incorrectly?!
Sorry, my English is bad.

NOTE: I don't see waht the function "close (2)  with the refresh  row" was used. (\active_scaffold-3.4.43\app\assets\javascripts\prototype\active_scaffold.js)

---------------- tables_controller ---------------------
```

class TablesController < ApplicationController
  active_scaffold :"table" do |conf|
    conf.label = 'Table'
    conf.actions.exclude :delete, :update, :search, :show
    conf.create.columns = [:name, :value]

    conf.action_links.add 'startup',  
                                        :label      => 'Startup',
					:method     => :post,
					:crud_type  => :update,
                                        :type       => :member,
					:inline     => true,
					:position   => :after

    conf.action_links.add 'shutdown',
                	                :label      => 'Shutdown',
					:method     => :post,
					:crud_type  => :update,
                                        :type       => :member,
					:inline     => true,
					:position   => :after,
					:confirm    => "Shutdown system?"

    conf.list.columns = Array[:name, :value]
  end
  @@running = false

  def startup
    msg = 'Error'
    msg = 'System is running' unless @@running
    @@running = true    
    render text: msg.to_s
  end

  def startup_authorized?(arg=nil)
    return true unless @@running
    return false
  end
  
  def shutdown
    msg = 'Error' 
    msg = 'System is stoped' if @@running
    @@running = false
   render text: msg.to_s
  end

  def shutdown_authorized?(arg=nil)
    return true if @@running
    return false
  end
end

```
---------------------------------------------------------
[tables_controller.txt](https://github.com/activescaffold/active_scaffold/files/1634179/tables_controller.txt)

![common](https://user-images.githubusercontent.com/33651840/34977842-3c234bdc-faad-11e7-8aec-7ee8a0852339.JPG)

**Comment by scambra** [comment]
Probably row is updated, because click and close again refreshes row.

I think problem is related to use class variable, which is kind of global variable. In development class variable can be assigned to false if class is reloaded (mabye only if controller is changed). In production, with multiple processes, depending which process process request, it can read different class variable, and closing action result will make an ajax request to update row, which can be processed by same process as previous request, or different process.

I don't understand why you have member action links for something not binded to each record, for member action links I would use some attribute in the record. For some global actions, I would use collection action links, and I would save in DB (e.g. using Setting model like rails-settings gem does), or I would save in memory in something shared by all processes, such as memcache or redis.

Also, I don't use action links with position for actions which change status without form, I use position false and flash[:info], flash[:warning] or flash[:error] to display messages (they will be displayed at top of records list), and row would be refreshed after action run, no need to close message.

**Comment by AlexGHub13** [comment]
Thank you very much for your answer. I will try  to upgrade my application.
Just, I was surprised because it worked on a oldest versions of rails and active_scaffold.
