### ISSUE TITLE
adding AS interferes with my app's UI

### ISSUE THREAD

**Issue by cpg** [activescaffold/active_scaffold#592]
I am not sure if this is a stated goal about AS, however, I did notice that a customer-facing part of my app changed after I added AS to an admin-only area of my app. This was unexpected. If it's not a goal, it probably ought to be? (as it would improve AS's usability even more)

It's in a jQuery-UI `ui-autocomplete` usage.

When `*= require active_scaffold` is included in the `application.css.less` the look of the `ui-menu-item`s in the main app changes. Also, when the `ui-state-focus` is added to an element (the user hovers or moves the cursor to select an item, the item's look changes radically

Here is the example. 
```
<ul class="ui-autocomplete ui-front ui-menu ui-widget ui-widget-content" id="ui-id-1" tabindex="0" style="display: none;">
<li class="ui-menu-item" id="ui-id-2" tabindex="-1">email1@example.com - Chris</li>
<li class="ui-menu-item" id="ui-id-3" tabindex="-1">email2@example.com - Bob</li>
<li class="ui-menu-item" id="ui-id-4" tabindex="-1">email3@example.com - Tom</li>
</ul>
```

**Comment by scambra** [comment]
You can use different layouts to your customer-facing and admin-area, with different manifests, so in your admin.css.less require active_scaffold, but don't require it in application.css.less

**Comment by cpg** [comment]
That is how I bypassed this issue.

Generally, I would consider this a good property to have in a gem that in many (most?) cases is used in conjunction with, or as part of,  a site proper. I would consider prefacing/enclosing ASs markup with AS-specific classes, for more modularity/cleanliness and unexpected bleeding of UI changes into the other areas of an app. Many less experienced users may be surprised if this happens.

**Comment by scambra** [comment]
I think it's done as you said, I looked for ui- classes in activescaffold stylesheets, and only one line doesn't enclosed with AS specific class. Probably your style is being overrided by jquery-ui-theme included with ActiveScaffold.

active_scaffold-ie.scss
56:.as-slider.ui-state-disabled {

active_scaffold_colors.scss
376:.active-scaffold .ui-droppable-disabled, .active-scaffold .ui-droppable-disabled.selected {

active_scaffold_jquery_ui.css.erb
3:<% require_asset "jquery-ui-theme" %>
10:<% require_asset "jquery-ui-theme" %>

active_scaffold_layout.css
221:.as-slider .ui-slider-range {
228:.as-slider.ui-state-disabled {
806:li.ui-draggable-disabled, li.ui-draggable-disabled label {

Also, I think is good practice using two manifest, one for front website and one for admin area, because admin styles are useless for non-admin visitors and they can download a smaller css file.
