### ISSUE TITLE
3.5.5 stable not supported on rails 5.2.3?

### ISSUE THREAD

**Issue by dgm** [activescaffold/active_scaffold#625]
A dependency was added to the gem spec for < 5.2.0 which seems odd to restrict maintenance releases.   I see it is gone in master, but the 3.5.5 tag still has `s.add_runtime_dependency('rails', '>= 4.0.5', '< 5.2.0')`

**Comment by scambra** [comment]
Because 3.5 branch doesn't work with rails 5.2, and fix for rails 5.2 was breaking on rails 4.0 and 4.1, so support for 5.2 was added to master branch, which will be 3.6

I usually don't add upper limit on version, so gem can be installed with newer versions when they are released. I got issue about error on rails 5.2, and I couldn't fix it without breaking compatibility with older versions, so I added rails 5.2 support only to master, and I had to set upper limit to rails versions on 3.5 line.
