### ISSUE TITLE
update_authorized?(record = nil) has null record object when checking permissions to edit

### ISSUE THREAD

**Issue by dennisbulgatz** [activescaffold/active_scaffold#638]
Had a strange bug.  In the list view, the "edit" action was correctly grayed out based on the update_authorized controller method.  However, when launching the "allowed edit" action, 403 error was returned. Tracked this down to the 'record' object being null.  Fixed as shown below by using the params to find the record.

def update_authorized?(record = nil)
    record ||= User.find(params[:id])
    current_user.has_role_name?("administrator") || (current_user == record)
  end

**Comment by scambra** [comment]
I think that's called from before_action update_authorized_filter, which runs before loading requested record. That's why update_authorized? is defined like this:

```ruby
    def update_authorized?(record = nil, column = nil)
      (!nested? || !nested.readonly?) && (record || self).authorized_for?(crud_type: :update, column: column, reason: true)
    end
```

Which will check User.authorized_for?(crud_type: :update), to forbid access when user can't edit any record.

You could define authorized_for_update? in User model:

```ruby
def authorized_for_update?
  current_user.has_role_name?("administrator") || (current_user == self)
end
```

**Comment by dennisbulgatz** [comment]
Thanks Sergio!  I have some model methods already to restrict column updates.  What are the pros and cons of using model vs. controller methods.  Does seem like a good idea to move everything to the model, just all the controls are in one file.

For example, in my app/models/user.rb

  def roles_authorized_for_update?
    return 'Only Admins Can Update Roles' unless current_user.has_role_name?("administrator")
    true
  end

Not sure if the reason is ever used or displayed, since the action is blocked?

in app/controllers/application_controller
	ActiveScaffold.defaults do |config|
		config.security.current_user_method = :current_user
                config.security.not_authorized_reason = true
	end

**Comment by scambra** [comment]
ActiveScaffold is designed to use authorization methods in the model, usually they are called through controller method (e.g. displaying action links calls controller method which calls model method by default), you can override default controller method if you need to check something available to controller only, such as params, for example allowing create only in nested listing can be done in controller only.

Sometimes model methods are called from helpers or views, such as checking authorized columns.

Reason is displayed on mouse hover when action is disabled. When action is unauthorized by class method, action link is not displayed, because action is not authorized for any record, but action link is displayed grayed out when action is unauthorized by instance authorized_for method, and reason is displayed as mouse hover (title html attribute). To display reason you must enable config.security.not_authorized_reason and instance authorized_for method must return string.

However reasons are displayed only for action links, they are not displayed when column is disabled. I could add support for that, but it would work only when config.update.show_unauthorized_columns is enabled, otherwise columns are not rendered in form.

**Comment by dennisbulgatz** [comment]
I tried moving the authorized checks to the user model, and they are not working.  

app/models/user.rb
  def delete_authorized?
    return 'Only Admins Can Delete' unless current_user.has_role_name?("administrator")
    true
  end

  def update_authorized?
    return 'Only Admins Can Update' unless current_user.has_role_name?("administrator")
    true
  end

Possibly there is an issue with the defaults. I moved out of the application controller and into 

config/initializers/active_scaffold.rb
ActiveScaffold.defaults do |config|
	config.security.current_user_method = :current_user
    config.security.not_authorized_reason = true
    #config.ignore_columns.add [:created_at, :updated_at, :lock_version]
end

**Comment by scambra** [comment]
The model methods should be authorized_for_delete? and authorized_for_update?

Pattern is <column>_authorized_for_<action>? to restrict access for a column in an action, <column>_authorized? to restrict access to column in every action, and authorized_for_<action>? to restrict action.

**Comment by dennisbulgatz** [comment]
Advice above got me going, and when done, did not find any bugs.  Thanks to Sergio!
