### ISSUE TITLE
The "reset" button on Field Search UI closes Search

### ISSUE THREAD

**Issue by dennisbulgatz** [activescaffold/active_scaffold#646]
The "reset" button in the field search Form UI closes the search window.  Should simply reset all values in the search to default, and leave the search form open for new search parameters.

**Comment by scambra** [comment]
Reset button in search forms (normal search form and field search) have always reset listing and close form. Reset button is not a input type=reset element, although it could call form.reset(). However, when list.refresh_with_header is enabled, all list element is replaced, so search form is gone anyway, so it is not so easy to avoid closing form when refresh_with_header is enabled.

I don't want to convert reset button in a simple reset function, because it would change behaviour of existing apps, although I can consider removing close form behaviour and call form.reset(), but it will have to reopen search form if refresh_with_header is enabled.

**Comment by scambra** [comment]
reset_form config has been added recently
