### ISSUE TITLE
Scaffolds redirect to individual controllers

### ISSUE THREAD

**Issue by gregschmit** [activescaffold/active_scaffold#650]
I am basically a brand new user to Active Scaffold. I started a Rails 6 app and added active scaffold, and I have a view where I render a couple scaffolds. They show up fine.

However, when I click on any of the actions (create, update, show, etc), they always redirect to the individual controller, rather than staying on the main page and just doing everything via AJAX. Is this normal? Is there a config I missed?

To just try to fix "Show", I tried adding this code in an initializer, and in the parent controller of the scaffolds:

```ruby
ActiveScaffold.set_defaults do |config|
  config.show.link.inline = true
  config.show.link.page = false
  config.show.link.position = :replace
  config.show.link.popup = false
end
```

I also tried adding that to the individual scaffolds, but nothing seems to work. I have included the js/css files.

**Comment by scambra** [comment]
Hi

You don't need to set popup or page if you set inline, setting inline to true will set others 
to false. Also, inline is default behaviour.

Have you added assets pipeline to your project? I think rails 6 doesn't use assets pipeline 
for JS anymore, but active scaffold doesn't work with webpacker yet. So you need to create 
application.js, add require active_scaffold, and add javascript_include_tag 'application' to 
your layout. You can check issue #624, mainly these comments:
https://github.com/activescaffold/active_scaffold/issues/624#issuecomment-612399008[1] 
https://github.com/activescaffold/active_scaffold/issues/624#issuecomment-632838632[2] 

Probably generator needs to be fixed to setup assets pipeline when installed in rails 6, 
because changing active scaffold to work with webpacker will take longer. Once it works 
with webpacker, maybe a flag can be added to use assets pipeline instead of webpacker, 
in case someone still wants it.

Regards

El lunes, 19 de octubre de 2020 17:53:12 (CEST) Greg Schmit escribió:
> I am basically a brand new user to Active Scaffold. I started a Rails 6 app
> and added active scaffold, and I have a view where I render a couple
> scaffolds. They show up fine.
> 
> However, when I click on any of the actions (create, update, show, etc),
> they always redirect to the individual controller, rather than staying on
> the main page and just doing everything via AJAX. Is this normal? Is there
> a config I missed?
> 
> To just try to fix "Show", I tried adding this code in an initializer, and
> in the parent controller of the scaffolds:
> 
> ```ruby
> ActiveScaffold.set_defaults do |config|
>   config.show.link.inline = true
>   config.show.link.page = false
>   config.show.link.position = :replace
>   config.show.link.popup = false
> end
> ```
> 
> I also tried adding that to the individual scaffolds, but nothing seems to
> work. I have included the js/css files.



--------
[1] https://github.com/activescaffold/active_scaffold/issues/
624#issuecomment-612399008
[2] https://github.com/activescaffold/active_scaffold/issues/
624#issuecomment-632838632

**Comment by gregschmit** [comment]
Hmm, I am using both sprockets and web packer in my project, and I was definitely getting the active scaffold javascript included by inspecting the compiled application.js asset, but I'm going to try to override the assets in `list.html.erb` like that first link you provided.

Thank you, I'll close this for now and re-open if I have any specific questions.

**Comment by gregschmit** [comment]
Omg, very noob mistake, I forgot to include jQuery UJS.
